version: "2"

services:
  app:
    build: 
      dockerfile: ./app/Dockerfile
      context: .

    ports:
        - 8080:8080 # host:container
    
    volumes:
        - ./app/:/app
    
    depends_on:
      - db
  
  db:
    image: postgres:11.5

    environment:
      POSTGRES_PASSWORD: exchanger
      POSTGRES_USER: exchanger
      POSTGRES_DB: exchanger

  volumes:
    - ./postgres-data:/var/lib/postgresql/data