# TODO: ADD NGINX
version: '3.7'

services:
  categories_service:
    build: ./services/categories
    command: alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    # Dev
    volumes:
      - ./services/categories:/app/
    environment:
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=categories_db

  categories_db:
    image: postgres:12.1-alpine
    volumes:
      - ./services/categories/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
