version: "2"

services:
  app:
    build: 
      dockerfile: ./app/Dockerfile
      context: .

    ports:
        - 8080:8080 # host:container
    
    volumes:
        - ./app/:/app
    
    depends_on:
      - db
  
  db:
    image: postgres:11.5

    environment:
      POSTGRES_PASSWORD: books_exchanger
      POSTGRES_USER: books_exchanger
      POSTGRES_DB: books_exchanger