version: "2"

services:
  app:
    build: 
      dockerfile: ./app/Dockerfile
      context: .
    
    volumes:
        - ./app/:/app
    
    depends_on:
      - db
  
  db:
    image: postgres:11.5

    environment:
      POSTGRES_PASSWORD: exchanger
      POSTGRES_USER: exchanger
      POSTGRES_DB: exchanger
      
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  nginx:
    image: nginx:1.13.5
    
    ports:
      - 80:80 # host:container
    
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    
    depends_on:
      - app