version: "2"

services:
  app:
    build: 
      dockerfile: ./app/Dockerfile
      context: .

    volumes:
        - ./app/:/app
    
    depends_on:
      - db
  
  db:
    image: postgres:11.5

    environment:
      POSTGRES_PASSWORD: books_exchanger
      POSTGRES_USER: books_exchanger
      POSTGRES_DB: books_exchanger

  nginx:
    image: nginx:1.13.5
    
    ports:
      - 8080:80 # host:container
    
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    
    depends_on:
      - app