"""Changes password length.

Revision ID: 16fdd2a8f658
Revises: 44c06b8cb240
Create Date: 2019-12-21 15:19:43.275718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fdd2a8f658'
down_revision = '44c06b8cb240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
