"""Fix longitude field

Revision ID: efa00be550be
Revises: 441274279a4c
Create Date: 2020-07-21 11:04:12.345952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa00be550be'
down_revision = '441274279a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
